object: "FRONT_WING"
# object: "REAR_WING"

model_name: "test"

hidden_units: [500, 500, 500]

epochs: 500

checkpoint_epochs: 100

in_velocity: 1

rho: 1.225
mu: 1.81e-5

x_max: 1
y_max: 1
z_max: 1

Nf: 100   # num of collocation points -> pde evaluation
Nb: 100   # num of points to evaluate boundary conditions
Nw: 100   # num of points of the surface of the front wing to evaluate boundary conditions
Nu: 5     # num of points of real data