hidden_units: [50, 50, 50, 50, 50]

epochs: 3000

checkpoint_epochs: 100

in_velocity: 1

# rho: 1.225
# mu: 1.81e-5
rho: 1.
mu: 0.01

x_min: -0.5
y_min: -0.5
x_max: 1.5
y_max: 0.5

Nf: 10000   # num of collocation points -> pde evaluation
Nb: 1000    # num of points to evaluate boundary conditions
Ns: 1000    # num of points of the surface of the airfoil to evaluate boundary conditions
Nin: 1000   # num of points inside the airfoil to evaluate boundary conditions