# object: "FRONT_WING"
object: "REAR_WING"

model_name: "test"

hidden_units: [1000, 1000, 1000]

epochs: 10

checkpoint_epochs: 5

in_velocity: 1

rho: 1
mu: 1

x_max: 1
y_max: 1
z_max: 1

Nf: 1000   # num of collocation points -> pde evaluation
Nb: 100   # num of points to evaluate boundary conditions
Nw: 1000   # num of points of the surface of the front wing to evaluate boundary conditions
Nu: 5     # num of points of real data