model_name: "test"

hidden_units: [500, 500, 500]

epochs: 1000

checkpoint_epochs: 100

in_velocity: 1

rho: 1.225
mu: 1.81e-5

x_min: -1
y_min: -1
x_max: 1
y_max: 1

Nf: 100   # num of collocation points -> pde evaluation
Nb: 100   # num of points to evaluate boundary conditions
Ns: 100   # num of points of the surface of the airfoil to evaluate boundary conditions