model_name: "v1"

hidden_units: [1000, 1000, 1000]

epochs: 10

checkpoint_epochs: 5

in_velocity: 1

rho: 1
mu: 1

x_max: 1
y_max: 1
z_max: 1

Nf: 100   # num of collocation points -> pde evaluation
Nb: 100   # num of points to evaluate boundary conditions
Nw: 100   # num of points of the surface of the front wing to evaluate boundary conditions
Nu: 2     # num of points of real data